# Generated by Django 5.1.2 on 2024-10-24 23:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_usuario_dir_correo_alter_usuario_nom_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='workspace',
            fields=[
                ('cod_espacio', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proyecto', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('fec_creacion', models.DateField(default=datetime.date.today)),
                ('usu_modificacion', models.CharField(max_length=255)),
                ('fec_modificacion', models.DateField(auto_now=True)),
                ('usu_creador', models.ForeignKey(db_column='usu_creador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'espacios',
            },
        ),
    ]
