# Generated by Django 5.1.2 on 2024-11-21 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaTableros',
            fields=[
                ('cod_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nom_lista', models.CharField(max_length=25)),
                ('cant_tarjetas', models.IntegerField(default=1)),
                ('cod_tablero', models.ForeignKey(db_column='cod_tablero', on_delete=django.db.models.deletion.CASCADE, to='tableros.tableros')),
            ],
            options={
                'db_table': 'listas_tableros',
            },
        ),
    ]
