# Generated by Django 5.1.2 on 2024-10-25 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_alter_usuario_dir_correo_alter_usuario_nom_usuario'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tableros',
            fields=[
                ('cod_tablero', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tablero', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fec_creacion', models.DateField(auto_now_add=True)),
                ('cod_espacio', models.ForeignKey(db_column='cod_espacio', on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
                ('usu_creador', models.ForeignKey(db_column='usu_creador', on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
            options={
                'db_table': 'tableros',
            },
        ),
    ]
