# Generated by Django 5.1.1 on 2024-11-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListasTableros',
            fields=[
                ('cod_lista', models.AutoField(primary_key=True, serialize=False)),
                ('nom_lista', models.CharField(max_length=25)),
                ('cant_tarjetas', models.IntegerField(default=1)),
                ('cod_tablero', models.IntegerField()),
            ],
            options={
                'db_table': 'listas_tableros',
            },
        ),
    ]
