# Generated by Django 5.1.1 on 2024-12-26 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tarjeta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('cod_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('fec_creacion', models.DateField(auto_now_add=True)),
                ('fec_vencimiento', models.DateField()),
                ('cod_tarjeta', models.ForeignKey(db_column='cod_tarjeta', on_delete=django.db.models.deletion.CASCADE, to='tarjeta.tarjeta')),
            ],
            options={
                'db_table': 'tareas',
            },
        ),
    ]
