# Generated by Django 5.1.2 on 2024-12-11 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lista_tableros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('cod_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tarjeta', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=3)),
                ('usu_encargado', models.CharField(blank=True, max_length=10, null=True)),
                ('fec_vencimiento', models.DateField(blank=True, null=True)),
                ('fec_creacion', models.DateField(auto_now_add=True)),
                ('cod_lista', models.ForeignKey(db_column='cod_lista', on_delete=django.db.models.deletion.CASCADE, to='lista_tableros.listatableros')),
            ],
            options={
                'db_table': 'tarjetas',
            },
        ),
    ]
